### ISSUE TITLE
Write

### ISSUE THREAD

**Issue by ddmakadia1699** [rocky112358/ACS-ACR122U-Tool#2]
How to write ?

**Comment by xorhd123** [comment]
I figured out how to use this. But I am making other programs by applying it. An example would be tagging a card to print an "O" if the database and UID match, and an "X" if they don't. However, a problem arose. If you are not tagging the card, it will look like this

Traceback (most recent call last):
  File "c:\Users\PRO\AppData\Local\Programs\Python\Python310\Scripts\nfctool.py", line 20, in <module>
    connection.connect()
  File "C:\Users\PRO\AppData\Local\Programs\Python\Python310\lib\site-packages\smartcard\CardConnectionDecorator.py", line 54, in connect
    self.component.connect(protocol, mode, disposition)
  File "C:\Users\PRO\AppData\Local\Programs\Python\Python310\lib\site-packages\smartcard\pcsc\PCSCCardConnection.py", line 120, in connect
    raise NoCardException('Unable to connect', hresult=hresult)
smartcard.Exceptions.NoCardException: Unable to connect: ˝ş¸¶Ć® Ä«µĺ°ˇ Á¦°ĹµÇľú±â ¶§ą®żˇ Ĺë˝ĹŔ» ´ő ŔĚ»ó ÇŇ Ľö ľř˝Ŕ´Ď´Ů.  (0x80100069)

If I am not tagging the card, how do I wait for the code to tag the card? I am so desperate right now. And this is the code I made.

from time import sleep
from smartcard.util import toHexString
from smartcard.System import readers
from smartcard.Exceptions import NoCardException
import firebase_admin
from firebase_admin import credentials
from firebase_admin import firestore


cred = credentials.Certificate('nfctool-4d5c2-firebase-adminsdk-s5lwd-9f1f8273f8.json')
firebase_admin.initialize_app(cred)

db = firestore.client()

r = readers()

reader = r[0]

connection = reader.createConnection()
connection.connect()

cmd = ""

cmdMap = {"": [0xFF, 0xCA, 0x00, 0x00, 0x00]
}
COMMAND = cmdMap.get(cmd, cmd)
data, sw1, sw2 = connection.transmit(COMMAND)


data, sw1, sw2 = connection.transmit(COMMAND)

type(COMMAND) == list

UID = (cmd +toHexString(data))

CODE = "{'n': '"+ UID +"'}"

GHX = 0

while True:
    
    data, sw1, sw2 = connection.transmit(COMMAND)


    data, sw1, sw2 = connection.transmit(COMMAND)

    type(COMMAND) == list

    UID = (cmd +toHexString(data))

    CODE = "{'n': '"+ UID +"'}"

    CODE = "{'n': '"+ UID +"'}"
    GHX = 0
    try:
        
        docs = db.collection(u'2_5_').stream()
        
        for doc in docs:
            if CODE == (f'{doc.to_dict()}'):
                GHX += 1
            else:
                GHX += 0

        docs != db.collection(u'2_5_').stream()

        docs = db.collection(u'2_6_').stream()

        for doc in docs:
            if UID ==(f'{doc.to_dict()}'):
                GHX += 1
            else:
                GHX += 0
        if GHX == 1:
            print("O")
            sleep(1)
        elif GHX == 0:
            print("X")
            sleep(1)
        else:
            print("What?")
            sleep(1)
        
    except NoCardException:
        sleep(1)

**Comment by ERHash** [comment]
#7
